- hosts: node1
  tasks:
  - name: ansible create directory with mode setting example
    file:
      path: /tmp/devops_directory
      state: directory
      mode: "u=rw,g=wx,o=rwx"                            
